### ISSUE TITLE
KCT should reset ignition count when filling tanks - and other similar metadata

### ISSUE THREAD

**Issue by CorvusCorax** [magico13/KCT#115]
For example when playing with RO (realism overhaul) or other realism mods, many engines have a limited count of ignitions (often just one)

When one recovers a craft with RCT, then the remaining ignitions get succesfully displayed in the editor as zero. However the editor offerns no way to reset this count to the default.
The part keeps this property when removed and placed elsewhere in the editor, even when duplicated.
(but engines with ignitions=zero are pretty useless)

The current workaround is, to delete the engine completely and place a "new" one from the parts menu in its place. This resets the ignition count.

This however is time consuming - especially when a craft has many engines - messes up the staging order - looses other engine specific configuration (with RO, some engines have multiple configs for different propellants or versions) - and if the engines have been placed off-center or rotated, one has to basically rebuild the craft.

I worked around that by basically placing the entire engine section in a subassembly - which can be replaced as a whole.

Unfortunately the "load" button is unavailable when editing an existing KCT craft, so this "easy" way to return the craft to factory default is not possible and one has to "cheat" with subassemblies

How difficult would it be to allow (entire) craft loading in "edit mode" ?

The perfect solutions would be to reset all part metadata (ignitions, damage (in case of TestFlight, or other damage metadata stored), but also "used" scientific instruments) when clicking "fill tanks"

but i could live with the ability to re"load" the craft from its blueprint via "load" button to restore it to pristine condition (also would save a lot of time if the encountered damage was a little bit more severe than anticipated - like those flights where you took off with a complete spaceplane and landed with little more than a cockpit + spent parachutes)

**Comment by magico13** [comment]
I highly suggest you read the following [Wiki page](https://github.com/magico13/KCT/wiki/Tutorial:-Adding-New-Modules-to-be-Reset-on-Recovery-to-Storage) about adding new modules to reset on recovery. Engine ignition reset would likely be a trivial thing to add yourself.

Recovering through the KCT GUI is meant to be time consuming. It emulates just moving a vessel into storage straight from wherever it was last used, without any sort of reconditioning or repair. You're supposed to have to do everything manually because if you wanted "fresh" components you'd use the stock recovery and just use the parts out of the inventory (this emulates the vessel being brought in and all the parts fixed up until they're like-new).

It would be easy to change the code to "fix" the ship completely, but there's already a way to do that: build a new one. The inventory reduces build times drastically; with default KCT it's a 10x reduction in time (RP-0 has a different config, so you'll have to check the formulas to see what sort of reduction you'd get).

The two recovery methods have different uses and tradeoffs. The KCT recovery is when you want to quickly launch the *exact* same vessel, but perhaps refuelled and maybe with a part or two fixed up. Any damaged or used up components should remain damaged and used up (parachutes are an exception because engineers can fix those on EVA). The stock recovery + new build takes more time (still much less than a new build without first recovering the parts) since those parts are all examined, fixed up, rebuilt, etc so you have an essentially brand new ship.

Here's another comparison: KCT recovery is comparable to an airplane stopping at an airport and loading new passengers while getting some parts checked over to make sure they won't break during the flight. Stock recovery + rebuild is like the space shuttle; it's reusable but requires a bunch of time to fix up all the parts, but still less time than if you built it from scratch.

**Comment by CorvusCorax** [comment]
Thanks, that makes a lot of sense. That is realistic, with these early WAC aerobee engines, the engine itself was single use, even if recovered, you'd have to swap it for a new one, so having to do that is actually pretty realistic (although really annoying for reusage with RP-0 as even "reuseable engines" like the Merlin have their ignition limited right now, even though they could use the also present  TEA/TEB tank volume for that)

**Comment by magico13** [comment]
Regarding reusable engines and limited ignition, I added a feature into v1.3 that lets you reset modules only for certain parts. You could reset the ignitions on just those engines if you wanted. There's an example in [this post](http://forum.kerbalspaceprogram.com/index.php?/topic/83342-105-kerbal-construction-time-130-010616-unrapid-planned-assembly/&do=findComment&comment=2342458) that you should be able to adapt. I'll try to remember to update the wiki page with that same info.
