### ISSUE TITLE
Launch pad buying

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#117]
A couple questions:
1. How do new pads interact with pad upgrade level?
2. New pads are per-KSC, right?

Also, what was the other thing you said was new that I might want to configure?

**Comment by magico13** [comment]
If you mean what level do new pads start at, they should all start from level 0 and must be upgraded through the normal right-click mechanic. 

If you're asking how the mechanic affects the launchpad facility itself, when you switch between pads it calls the function that sets the level of the pad to upgrade/downgrade it (through the Upgradeables.UpgradeableFacility object for the launchpad) and it also sets the state of the DestructibleBuildings for the launchpad (so that each pad has its own level and destruction state). That annoyingly triggers the OnFacilityUpgraded event each time, so anything listening to that is going to have some problems.

New pads are per-KSC, correct. I considered expanding that to all buildings using the same procedure, but it really only makes sense for the VAB/SPH and Launchpad/Runway.

The other thing was that there's a new setting where you can have all the KSCs share a single upgrade pool, instead of each having their own. So when you get a new upgrade point you'd have to decide which KSC you want to use it at instead of every KSC getting a new point. Enabling that on an existing game would be a bad idea, but it could easily be disabled in those saves if you enabled it by default.

There also was a change to reduce issues with KSCSwitcher when starting a new game: KCT now properly gets the default KSC and doesn't require switching between two KSCs at the start of a new game.

**Comment by NathanKell** [comment]
Ah! Right! The pool. Thanks!

And re: the pads, awesome, couldn't have asked for a better setup. :)
