### ISSUE TITLE
Ideas: Should you be able to make multiple boosters and simply build and mount a payload?

### ISSUE THREAD

**Issue by ntimpe** [magico13/KCT#123]
I don't know about you guys, but especially in RO I standardize my boosters really quickly. My idea was that there be some UI element that allowed you to produce multiple boosters in advance, so that you just have to build your satellite and mount it to the booster before you launch. I guess you could build a booster and then recover it on the launch pad, but I feel like there should be an easier way.

Also, regarding the construction time, in reality it is usually cheaper and faster to build something that you have already built before. The Delta II had drastically lower per-unit production costs at peak production than when they first started making them because they had the facilities and procedures used to produce them down to a science. My suggestion is that the price of a specific item decreases the more of it you build, perhaps asymptotically so that you can't make Rapiers for 0 credits if you build enough of them.

Any thoughts on this?

**Comment by magico13** [comment]
Firstly, if you're asking for balances while using RP-0 then you'll want to bring this up in their forum thread, since RP-0 uses wildly different balances than stock KCT.

The inventory system and the "edit" system already handles your first request pretty well. You can already build a bunch of launchers and keep them stored, then build your payload later. You then have two options: scrap both (through the "\*" button, rather than launching them which is slow and inefficient) and rebuild the vessel from those parts (builds using entirely inventory parts are built in about 1/10 of the time compared to a new vessel in stock KCT); or scrap ONE (ideally the cheaper one) and "edit" the other (once again, through the "\*" button) then attach the parts for the other at a much reduced build time. If you have two or more build queues you can build things very quickly this way.

Example: You have a booster and a payload and the payload costs way more than the booster. You scrap the booster and edit the payload, attach the booster in the editor, then save the edits. Now you wait for slightly longer than the time it takes to build the booster from entirely inventory parts (1/10 of the time it takes to build the booster from scratch).

Regarding the other suggestion: subsequent builds are already factored into construction times through the "Effective Part" formula. Every time you finish construction on a vessel, the part tracker updates for every part on the vessel (ignoring duplicates). So if you build a ship with a command pod, flea, and two radial parachutes then the tracker for each unique part will increase by one. For stock KCT after 4 builds using the same exact parts the vessel will take half the time to be built. This greatly encourages standardization of launchers, since you can quickly make the launcher build time nearly negligible compared to the payload build time.

**Comment by magico13** [comment]
Since I think this is fairly well covered by existing functionality and I'm doing some cleanup of old issues, I'm going to close this. If you'd like to bring up the idea of reducing costs for multiple builds of a part, you could maybe submit that as an idea for [ScrapYard](https://github.com/magico13/scrapyard), though I don't see that being added to ScrapYard proper but instead as a separate mod that utilizes ScrapYard. I don't believe that is something I will work on, however.
