### ISSUE TITLE
Installation Help! Untested 1.2 Pre-Release 

### ISSUE THREAD

**Issue by Meekers** [magico13/KCT#148]
I know to merge the gamedata folders but I am not sure what to do with the rest of the files and whenever I open up the game the mod doesn't work. Help @magico13

**Comment by petersohn** [comment]
First, the untested pre-release version won't work. You have to download the development branch from git.

Second, you'll have to compile the code. For that, you need some C# compiler, like Visual Studio or MonoDevelop. Then, you have to open and build the solution, and copy the generated `KerbalConstructionTime.dll` file to your `GameData`. You'll prbably also need to change the paths to KSP's dll files in Project References, because they are needed to build the code.

**Comment by Meekers** [comment]
@petersohn welp, i guess it looks like I'm waiting for the thing to come out. I have no idea what you mean. Thanks tho

**Comment by magico13** [comment]
There's a pre-release that doesn't require too much work to install over
here:
http://forum.kerbalspaceprogram.com/index.php?/topic/62900-kerbal-construction-timestagerecovery-dev-thread/

**Comment by magico13** [comment]
Full downloads of the dev builds can be gotten from here: http://magico13.net:8080/job/Kerbal%20Construction%20Time%20Beta/ They are installed as normal, so I'm going to close this issue as it is old and not relevant anymore. If anyone has any issues with installation, let me know (preferably on the forum, but here is ok too)
