### ISSUE TITLE
Free part unlocks when trying to research a node that is already being researched.

### ISSUE THREAD

**Issue by legacynl** [magico13/KCT#152]
It seems that KCT purchases every part for free when I try to research a tech-node that is already being researched.

I'm using the 1.2 version with RSS and RP-0, so maybe it's due to some weird mod interaction.

The code that seems responsible is "ResearchAndDevelopment.Instance.AddScience(tech.scienceCost, TransactionReasons.RnDTechResearch);". I'd be happy to make a pull request myself but I can't find any documentation on "ResearchAndDevelopment".

**Comment by magico13** [comment]
To confirm, you did back out of the R&D UI and go back in to verify that
the node is still unlocked, and further went through an entire scene change
and back to verify it's unlocked? KCT gives you your science back when you
try to unlock a node you're already researching since A) I can't easily
prevent the purchase from happening so you'd just lose science if I didn't,
and B) that allows you to unlock the node temporarily so you can purchase
later nodes on the tree. In any case, the node should relock when you exit
the R&D screen so that when you come back into it they are locked again. At
no point should you be able to use those parts until the node is completed.

**Comment by legacynl** [comment]
Changing scene from r&d to ksc and back DID revert the parts back to the unpurchased state.
Because I wanted to test, I exited to KSC, saved & returned to R&D. To my suprise all the technodes I'm researching now have all the parts purchased! After reverting to the same save the parts are all unpurchased again.

I think that finishing research on a tech node while the parts are 'purchased' will actually unlock all parts for free.

I'll check if i can recreate the issue on a 'clean' savefile.

**Comment by legacynl** [comment]
I think I figured out the problem. I was playing without tech unlock costs. Usually I do, the R&D center shows unlock costs, and I couldn't check in the difficulty settings (it's not in there). 

Sorry for wasting your time!
