### ISSUE TITLE
KCT Data Error "Game will be unplayable" etc...

### ISSUE THREAD

**Issue by sluvine** [magico13/KCT#155]
I'm getting an error when loading a saved game using KCT - seems to have something to do with MagiCore (I have version 1.2.4.0 installed, which is what came with the dev build).

Running KSP 1.3 and the latest dev version of KCT and StageRecovery.

The log has a ton of errors relating to MagiCore.MathParsing.ParseMath (Method not found). I'm going to try and see if there's a later version of MagiCore I should be using, but again, this one is the one that came with the version of KCT that I'm working with currently.

[output.txt](https://github.com/magico13/KCT/files/1074644/output.txt)

**Comment by magico13** [comment]
You have a duplicate MagiCore at GameData/MagiCore.dll. Delete that one and it should be fine. MagiCore 1.2.4 is the same as MagiCore 1.2.5 so you already have the latest.

**Comment by sluvine** [comment]
Thanks, I totally missed that there was one sitting directly in the Game Data folder. I will remove the GameData/MagiCore one and report back.

**Comment by magico13** [comment]
It's happened a few times now so I should probably put up a warning somewhere. If it works then just close this issue and (optionally) leave a comment.

**Comment by sluvine** [comment]
I gave it a shot and ended up with the same result.

As a quick bit of context - I updated to v 1.3 using the KSP patching tool and then went through, mod-by-mod, grabbing the latest available versions that were compatible with 1.3.

Obviously everything was backed up prior to the patching or updating of mods (so I can roll back at any time really). So when I first got the error with KCT, I looked at the data in persistent.sfs and it was more-or-less empty (after exiting KSP). I thought maybe something got messed up in either the patching process or when KCT first ran. So I tried copying in the SCENARIO {} block for the KerbalConstructionTimeData to see if that would help, but no joy.

I have noticed that in the persistent.sfs for my save, it's now showing in LoaderInfo:

MagiCore v1.0.0.0 = True
...
KerbalConstructionTime v1.3.4.2 = False
...
KerbalConstructionTime = True

...and a whole lot of other stuff. Not sure if that is relevant or not, but it struck me as strange that there would be two KCT entries as well as a MagiCore version that doesn't seem to represent the actual version being used.

I'm going to start from scratch, this time without the extra MagiCore directory, and see if I have any better results.

**Comment by sluvine** [comment]
Actually, before I did the "start from scratch" option, I tried replacing the MagiCore.dll in the GameData directory with the 1.2.5 version I had downloaded from your Jenkins page... then copied in my old KerbalConstructionTimeData from persistent.sfs, fired up KSP, and everything is wonderful again.

Appreciate your help, I really just needed to read more carefully through the logs, but your guidance got me there way faster than if I had just aimlessly poked around.

Oh, and thank you for this excellent mod, by the way. It seriously is a must-have for me at this point. Makes the game so much more enjoyable. I'm long overdue for donating some patreon support. Thanks again for everything.

**Comment by magico13** [comment]
The MagiCore shows up as 1.0 because I can't change the version of the assembly without breaking everything every time it updates. It's a .NET problem that can't be fixed on my side, basically if you compile against a particular .dll you must use that same version or it'll break, even if it should be compatible. The workaround is to set it to version 1.0 and never change it. I think I can change the "file version" rather than the actual assembly version, which will cause it to show up as "1.0.0.0 / 1.2.5.0" instead, which is definitely better.

I'm happy to hear it's working again. Typically if I get that error popup I immediately Alt-F4 KSP so that it doesn't overwrite the save file with bad data. I should probably try to find a way to not "corrupt" the save if someone does exit the normal way or changes scenes. or at least automatically back up the save when that popup occurs.
