### ISSUE TITLE
"Warp to complete" alters UI visibility

### ISSUE THREAD

**Issue by vtdmhd** [magico13/KCT#37]
Don't make displayed list of vessels invisible on click. users have to open that list again to rollout/launch the vessel

**Comment by magico13** [comment]
This is a side effect of letting the user minimize the VAB and SPH build lists. You can't normally select the same button on a toolbar (those buttons are a unity toolbar) so in order to act on it properly there's a listener that waits until the GUI changes. Unfortunately, that includes pressing any other button, including the warp to complete.

I may be able to switch back from a toolbar to individual buttons for the VAB/SPH/Tech tabs, but it's more work than it's worth at the moment, and then they no longer will highlight when selected.
