### ISSUE TITLE
"Launch" tooltip in VAB follows the cursor forever if the button was pressed

### ISSUE THREAD

**Issue by vtdmhd** [magico13/KCT#39]

**Comment by magico13** [comment]
I'm not sure how to fix this, since the stock game has this problem too with the save button. A temporary fix is to hover the cursor over the launch button for even a split second afterward. I think it's related to locking the editor after a button press, but if it's between accidentally disassembling your ship and having a tiny tooltip get in the way, I'd take the tooltip.

**Comment by jwvanderbeck** [comment]
This always bothers me.  I actually disable the launch button override just so I don't see the stuck tooltip :)

**Comment by fingerboxes** [comment]
I just submitted a PR to fix this.

**Comment by magico13** [comment]
PR accepted, build server has built it. I'm planning on taking care of some things this weekend, hopefully getting a new update out afterward. A project I was working on got some stuff shifted to different people, so I've been trying to get some things fixed with the opened up time.
