### ISSUE TITLE
build list dissapears after selecting new launch site in RSS (6.4x)

### ISSUE THREAD

**Issue by chootrain** [magico13/KCT#50]
I start building a ship on one launch site, change the launch site, and the ship list is cleared.
All the 'points' are reverted as well; and I dont get the money back for the missing ships

**Comment by magico13** [comment]
All of the launch sites have their own upgrades and build lists, as was requested by NathanKell. If you want to launch something from a site, you have to build it at that site. They should all reappear when you switch back to whatever site you were at. Let me know if that's not the case.

**Comment by chootrain** [comment]
you're right. I found what the problem is: The launch site that the game defaults to at start up (the original Kerbal space center) is not part of 'available' launch sites. So when I switch to a different site, I cant switch to the default KSC where I began building my ships.

Basically there are 2 KSCs, and one of them cant be accessed after you switch the sites (unless you restart the game). This does cause some confusion though :p

I'm guessing this is more of an issue with RSS, so I'll bother Nathan about that. Thanks for the help.

**Comment by magico13** [comment]
I think it's an issue on my side actually. KCT has a "default" launch site called "Stock" that it uses and it can't read the RSS data until you actually switch to a site. Basically, as long as you actually select a site after starting a game then everything should be in sync properly. It should be that when you reload the game it selects the "last used" site, but I haven't done much testing with RSS since 0.25.

**Comment by chootrain** [comment]
Gotcha, I'll try to remember to do this. Thanks.

**Comment by magico13** [comment]
At some point in the past I fixed this so that KCT would use the default KSC Switcher site when starting a new game, which I believe was all that was required for this. It's always safest to go into the tracking station and manually select a launch site.
