### ISSUE TITLE
mod engine not the inventory gui

### ISSUE THREAD

**Issue by supermerill** [magico13/KCT#60]
I have a weird bug (with the build #104, win 32b):
in the part inventory, the engine tab is somewhat buggy:
- some of engine part from my mod are in the inventory in the save file but not in the gui.
- when building a vessel: one time, it refresh the engine tab correctly, others time, it draw the Ctl tab instead.

note:
- bp calculation is ok, it's only a gui bug.
- part inventory is not refresh/clean when [quit to main menu] -> load other save

Others tabs are ok.

**Comment by magico13** [comment]
> some of engine part from my mod are in the inventory in the save file but not in the gui.

Do these properly use the engine part category rather than the deprecated propulsion category? If they're still using propulsion then they might not show up in the inventory but will still be in the save file (and will be used properly).

I'll have to look into the other things. It shouldn't be switching to the control tab, but I can imagine a cause for that.

The part inventory should be reset, not sure why it wouldn't be. Here's the code that should be doing it:
````
PartTracker = new Dictionary<string, int>();
PartInventory = new Dictionary<string, int>();
````

**Comment by supermerill** [comment]
> Do these properly use the engine part category rather than the deprecated propulsion category?
Nop, thanks for the tips.

>It shouldn't be switching to the control tab,
and fuel tank switch to propulsion. Ctl to Struct, but pod do not switch.

>The part inventory should be reset
It's not reset in my installation when entering the vab. I need to uncheck/recheck the tab (if i just scrap a finished build, if i come from an other save).
