### ISSUE TITLE
build#121 settings aren't persisted.

### ISSUE THREAD

**Issue by Rodhern** [magico13/KCT#79]
I create a new career with a 'fresh install' of KCT#121.
I select "1 - Choose a Preset" and the default preset is selected automatically selected.
I change "Override Launch Button" to off and "Debug Logging" to on. (I know they aren't preset specific).
 I enter the VAB, at first everything is normal. Then when I use a command pod (first item placed) the settings are forgotten. I exit the VAB and enter KCT Settings to see that "Override Launch Button" and "Debug Logging" reverted (to on and off respectively).

**Comment by magico13** [comment]
I think I know what the problem is, thank you for catching it! It's a simple matter of not actually saving the settings at any point, then reading from the settings file. You can still edit the settings file directly if you need those active in the mean time.

Also, for issues with the dev versions I typically prefer they're posted in the [development forum thread](http://forum.kerbalspaceprogram.com/threads/69310-Kerbal-Construction-Time-StageRecovery-Dev-Thread) since it makes it easier to see what's been reported already, but doing it on GitHub works as well (both would be fine as well).

**Comment by Rodhern** [comment]
Ahh, sorry the dev. forum it is then :-)
