### ISSUE TITLE
Add variables to ReconditioningFormula

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#83]
It would be very helpful if the BP cost, as well as the funds cost, of rollout could be set using all the variables in the rollout cost formula, since the same things that affect rollout cost would also affect rollout time.

Also a a variable for whether it's rollout or recondtioning would be great, since rollout will depend on how complex the vehicle is but reconditioning pretty much just mass.

(And thanks so much for adding rollout costs!)

**Comment by magico13** [comment]
First part is super easy, I can just add those variables. Second part (whether it's reconditioning or rollout) isn't nearly as easy, since internally they're the same exact thing. The formula is calculated once, then the rollout/recon split is applied to them to determine how much is for rollout, and how much is for reconditioning. In default KCT, they're both just mass based and it gives a way to define whether you want to wait entirely before launch, entirely after, or some split.

I'm not too sure I'll be able to disconnect them in any easy way. If it's something you really want, I can try.

**Comment by magico13** [comment]
Eh, I take that back. They're intertwined but I should be able to make it happen without as much work as I thought.

**Comment by NathanKell** [comment]
It's not an extreme priority in the least. It would be very nice, of course, but it's certainly survivable to go without. :)

**Comment by magico13** [comment]
I think I've got it implemented correctly now, just in the process of testing. First test failed because I tried to use the same variable twice, and dictionaries aren't a big fan of that.

**Comment by magico13** [comment]
Done! I have to update the documentation still.

*IMPORTANT NOTE* In this formula and the RolloutCosts formula, I had to change [E]=Editor Level to [EL]=Editor Level due to a conflict.

Additionally, you must now explicitly include the rollout/reconditioning split in the formula. Simplest way is by adding this to the end of the formula
> *abs([RE]-[S])

where [RE] is 1 if reconditioning or 0 if rollout/rollback/or recovery and [S] is the split (between 0 and 1).

**Comment by NathanKell** [comment]
Awesome! :)
