### ISSUE TITLE
Disabling formulae

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#84]
In the wiki, you mention a negative value disables a rate. Does this also hold true for formulae?
Right now I have
InventorySaleFormula = 0
ResearchFormula = 0
UpgradeResetFormula = 99999999
UpgradeScienceFormula = 99999999

can they be set to -1 to hide the features?

**Comment by magico13** [comment]
InventorySaleFormula you should keep at 0, but the rest can be set to -1 to disable them. With InventorySaleFormula at 0 you can still clear out the inventory, but you won't get any upgrade points from it. If it's set to -1, you'd lose an upgrade point (not each time, you'd just have one less than you otherwise should).

All the ones where a negative value disables them should say so in the documentation. For example:
>ResearchFormula = "[N]*0.5/86400"
    Purpose: Defines how much science is earned for building vessels. Negative means disabled.
    Variables: N=number of upgrades of Research purchased, R=R&D center level

If you're unsure though, feel free to ask.

**Comment by NathanKell** [comment]
Wow, I clearly fail at reading docs. Sorry about that. :]
