### ISSUE TITLE
Kerbin vs home

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#92]
Please use body == Planetarium.fetch.Home (or body.isHomeworld) instead of just checking the name string is "Kerbin" :)

**Comment by NathanKell** [comment]
Also, if you grab KerbinMass from a named body, or hardcode it, please grab mass from Planetarium.fetch.Home.mass

**Comment by magico13** [comment]
Can do. I'll make those changes tonight. Large enough bug that I might push
a new release rather than waiting for any more content.

**Comment by NathanKell** [comment]
Awesome! Thanks much! I'll push an RP-0 with the preset changes too and we'll be all golden! :)

**Comment by magico13** [comment]
Quick question: Is KCT actually giving wrong values for things with RSS? I'm pretty sure any time I reference Kerbin, if it can't find that it looks for Earth. For instance, in the simulation cost function:
```
CelestialBody Kerbin = GetBodyByName("Kerbin");
if (Kerbin == null)
    Kerbin = GetBodyByName("Earth");
```

I'll still put that change out tonight, but I don't think it should be having any issues with RSS at the moment.

**Comment by NathanKell** [comment]
Well, it's using the non-Kerbin sim line, which is what brought it to my attention. However, let me verify I am on the correct KCT before bugging you further. :]

**Comment by NathanKell** [comment]
Was on 1.2.0. Let me see if 1.2.1 fixes.

**Comment by magico13** [comment]
Hmm, those should also be [checking for Earth](https://github.com/magico13/KCT/blob/master/Kerbal_Construction_Time/KCT_GUI.cs#L899). If I can just compare the selected body to the home body, then that's actually easier. Never realized that the home body was stored somewhere for some reason.

**Comment by NathanKell** [comment]
Well, one reason might be that before KSP 1.0, it was *never used* :P (Mu changed it to actually be used in 1.0)

As to the issue: yeah, I don't see any reason in the code why it would be failing. And, in fact, it was *not* failing. Instead somehow I'd gotten on the Custom preset so the changes to the preset cfg weren't being applied. It's working properly now. Sorry. :\

**Comment by NathanKell** [comment]
So, anyway, using Home is safest IMO, and certainly cleaner, but the existing code does work in this special case, so...at least as regards me, it's not an issue. :)

**Comment by magico13** [comment]
I'll still change it to use home. It'll make the code clean, clear, and under control (which may or may not be a reference to a face wash commercial).

While you're making changes to the Preset, do you mind keeping an eye out for what happens when you load an existing save that uses said Preset.

What should happen: KCT grabs the data from the Preset .cfg file and overwrites the one in the Save folder.
What might happen (and is wrong behavior): KCT sees that the saved settings don't match the Preset and it switches to Custom.

I'm afraid the second thing is happening. If you happen to confirm that, open up an issue for it. I'll also try to test that tonight.

Also, I'm still going to leave this open until I make the change. It's like a checklist.

**Comment by NathanKell** [comment]
Gotcha. :)

And, sadly, expect a new issue in 3...2...1....
